version: '3.4'

services:
  web:
    build: ./Onboarding
    ports:
        - "5000:80"
    depends_on:
        - db
    restart: always
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      SA_PASSWORD: "YourStrongP@ssword"
      ACCEPT_EULA: "Y"
